#!/bin/bash

# If the site is on SiteGround:
#   rsync -rvz -e 'ssh -p 18765' [ssh alias, e.g. horner]:.jb_backup/ /Users/computer14/Desktop/
# If connecting to a standard port:
#   rsync -rvz [ssh alias, e.g. horner]:.jb_backup/ /Users/computer14/Desktop/\n\n" | tee -a "${backup_log_file}"

rsync -rhvz -e 'ssh -p 18765' --progress $1:.jb_backup/ /Users/computer14/Desktop/

